### ISSUE TITLE
touchtokeys width and height are switched

### ISSUE THREAD

**Issue by joemck** [hax0kartik/rehid#11]
I was trying to set up some touchtokeys mappings and it wasn't working how I expected.
The touchtokeys mappings that mikahjc's builder website creates have press in the form of [X, Y, Width, Height], like I would expect. However Remapper.cpp around line 300 reads it as [X, Y, Height, Width].

I think I may be the first person to try to map touch regions that aren't square.

**Comment by mikahjc** [comment]
Whatever rehid says in code is the source of truth, so that's my bad on the builder's part. I'll get that fixed.

**Comment by mikahjc** [comment]
@joemck I just deployed a new version of the builder that should have this fixed.
