### ISSUE TITLE
Rehid not working on Virtual Console

### ISSUE THREAD

**Issue by LeedleFace** [hax0kartik/rehid#15]
I tried using rehid on a virtual console game (the legend of zelda minish cap) and it just didn't swap the buttons. It works just fine on all the non virtual console games, even homebrew apps.

**Comment by hax0kartik** [comment]
Virtual console is not supported with rehid.

**Comment by FoxBlocks** [comment]
It doesn't work because GBA Virtual Console games put the 3DS in a special GBA-compatible hardware mode that 3DS software, including rehid, are incompatible with. rehid will work just fine on non-GBA Virtual Console titles (I use rehid on my GB and GBC games).
