### ISSUE TITLE
Swapping circle pad up and down to dpad up and down doesn't work

### ISSUE THREAD

**Issue by Goldfire345** [hax0kartik/rehid#16]
So I got this tool for playing ninja battle heroes because I wanted to swap the movement controls away from the character circle pad to the dpad to play it more comfortablely as a 2d platformer (no In game button remapping unfortunately) 
Only it doesn't fully work. swapping circle pad left and right to dpad left and right works fine. But when I do the same with cpad up and cpad down the dpad doesn't read properly as cpad up or down. Is there any way to fix this?

**Comment by hax0kartik** [comment]
https://discord.gg/hyuvmb9
Join this server, I'll help you out there.
