### ISSUE TITLE
Rehid folder

### ISSUE THREAD

**Issue by KekkoGH** [hax0kartik/rehid#23]
First of all I apologize because it is not a real problem but I don't know where to ask for help about that.
The guide mentions a "Rehid" folder, but never says where it is or where it should be created, i wanted to remap the buttons for just one game, so i would need this folder from what i understand.
Sorry again.

**Comment by hax0kartik** [comment]
Hi you need to create the rehid folder at the root of your sd card. This is where you will see a "Nintendo 3DS" folder.
