### ISSUE TITLE
Feature request, rebind key combo to be home button press

### ISSUE THREAD

**Issue by azlekayn** [hax0kartik/rehid#30]
Hi there, 

I've managed to break the connector for my home button like an idiot.

So my home button doesn't work any more, I'd like a feature to be able to rebind a key combo ie (ZL+ZR+Sel) to do a home button press. 

Currently This isn't possible as far as I can tell or test. 

Thanks

**Comment by hax0kartik** [comment]
This is possible to do in the latest release. Use Remap Builder to build the remap. https://mikahjc.github.io/3dsRemapBuilder/config
