### ISSUE TITLE
[Question] Ability to remap Home button?

### ISSUE THREAD

**Issue by felixsrg** [hax0kartik/rehid#6]
Hello there,

I've been really enjoying this homebrew's capabilities on my o3DS and recently got a broken New 3DS XL. I fixed it and it's now working, but its Home Button refuses to work even after changing the ribbon cable.

Anyway with that situation, I was wondering if it would be possible in the future to remap the Home button to a button combo.

Thank you again for this amazing utility!

**Comment by hax0kartik** [comment]
Check the discord server for a test build

**Comment by hax0kartik** [comment]
Fixxed by commit 4ea0bc73b015a88224bba3d8074bad394db88383
