### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by itchyd** [hax0kartik/rehid#7]
https://youtu.be/3kFlzD2_inU

When I close the lid for awhile leaving the console on and come back to my game (this is dqm2) it sometimes gets in this state.  No buttons do anything except the home button but that is no help because even on the home screen I can't do anything.

It's a big problem because I can't save my game when it's in this state.

**Comment by itchyd** [comment]
The power button must be pressed 2x to turn the console off and escape this state.

**Comment by hax0kartik** [comment]
[0004013000001D02.zip](https://github.com/hax0kartik/rehid/files/6638171/0004013000001D02.zip)
Try this out, extract the contents of  the zip to `/luma/titles/`

**Comment by itchyd** [comment]
Sorry it's hard to prove a negative, and I just installed this.  Let me try it for a few days.

**Comment by itchyd** [comment]
Nope that did not fix it.  All I have to do is open and close the system a few times.  Here's the remaps I'm using.  The game is Dragon Quest Monsters 2 fan translation.  

![dqm2 rehid](https://user-images.githubusercontent.com/291878/122437116-6780af80-cf67-11eb-9955-9ee8f603ec57.png)

**Comment by hax0kartik** [comment]
Seemingly fixed in latest commit.
