### ISSUE TITLE
Home Menu mappings reset to default after closing a title

### ISSUE THREAD

**Issue by radical6** [hax0kartik/rehid#8]
The global mappings work on the Home Menu at boot, but resets back to default after closing a game/title.

**Comment by hax0kartik** [comment]
Open a game again and they'll work again. This is bt design and rpobably not the best desigh imho.

**Comment by Infernotex** [comment]
Will this be fixed in the future?

**Comment by hax0kartik** [comment]
Fixed in latest rehid version
