### ISSUE TITLE
Swapping the D-PAD with the C-Pad mappings causes both the D-Pad and the C-pad to behave the same

### ISSUE THREAD

**Issue by CornCake** [hax0kartik/rehid#9]
Edit: I sneezed and posted the issue accidentally before typing the description. Sorry about that. 

At the 3DS Remap Builder, when I set mappings both for Buttons and Circle Pad, one takes effect first and the other then imitates the changed controls, rather than the base controls of the console.

Like, moving the Cpad works as a Dpad button press, and as the Dpad is set to behave as the Cpad, it registers a Cpad direction. And as the Cpad is set to behave as the Dpad, it triggers a Dpad button press, which registers as a Cpad movement, and it goes on like that.
As a result, the Dpad and the Cpad both behave as only one of them, and it's like you're pressing the same button many times at once.

It appeared to me that the "D-pad to C-pad" and "C-pad to D-pad" switches in General Options take place first, the Buttons settings second and the Circle Pad settings last. 
I say this because mapping Buttons and Circle Pad with both switches disabled, the C-pad registers the D-pad which causes it to behave as the C-pad again, while the D-pad behaves as the C-pad as it should except for it being registered a lot of times at once, causing menus to become near impossible to navigate. The switches will always override any mapping from either settings sections.

I'm trying to play Metroid: Samus Returns on an o3ds. Thank you.

**Comment by hax0kartik** [comment]
Fixed in master
